[package]
name = "learn_rust_game_engine"
version = "0.1.0"
authors = ["Parvu Eduard <parvueduard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.23.0"
nalgebra = "0.23.0"
ash = "0.31.0"
